### PR TITLE
Support ASR evaluation

### PR DESCRIPTION
**Pull request by teelisyys**

### CODE REVIEW

**Review by thisismatu — CHANGES_REQUESTED** [review]
A few things;

The docs for evaluate sub-commands are missing. These need to be generated.

The transcribe command complains about some JSON error when adding a single WAV file. In [the design doc](https://docs.google.com/document/d/15xy77EvZUCkYlffVLbXD4rYgIOOD1_OFL1XF1tHPscs/edit#heading=h.q0cslzx6oqpz) the idea was that it should accept both single files or JSON Lines files if you wanted to send multiple files. As a user i now don't have the faintest idea of what format this command expects and this renders the command useless.

**Review by thisismatu — COMMENTED** [review]
Looks great, thanks!

The only thing i'm struggling with at the moment is that when transcribing a single file i always get the same `Closing file failed: invalid argument` error.

```bash
./bin/speechly transcribe ./ndgt.wav -a 962f1ea7-9970-47ab-b7e6-bc9c88ed21d0
```

**Comment by thisismatu** [comment]
Also, noticed that `annotate`, `evaluate asr` and `evaluate nlu` all take APP ID as positional argument. For the sake of unity, i would love that `transcribe` would follow suit.

**Comment by thisismatu** [comment]
Also, as noted in todays demos, instead of printing all the results when using `evaluate asr`, perhaps it could work in the same fashion as `evaluate nlu` i.e. only print out the things that were wrong.

**Review by thisismatu — APPROVED** [review]
👍

**Review by langma — APPROVED** [review]

**Pull request merged**
